apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-service-deployment
  labels:
    app: filebeat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat-service
  template:
    metadata:
      labels:
        app: filebeat-service
    spec:
      containers:
        - name: filebeat-service
          image: registry.hub.docker.com/sourabhpayal/filebeat-service
          volumeMounts:
            - name: log-pv
              mountPath: /
              subPath:
            resources:
              { }
---
apiVersion: v1
kind: Service
metadata:
  name: filebeat-service
spec:
  selector:
    app: filebeat-service