kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: log-pvc
spec:
    accessModes:
      - ReadWriteMany
    storageClassName: standard
    resources:
        requests:
            storage: 32Mi
