apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: poshak-elasticsearch
  labels:
    app: poshak-elasticsearch
spec:
  replicas: 1
  serviceName: poshak-elasticsearch
  selector:
    matchLabels:
      app: poshak-elasticsearch
  template:
    metadata:
      labels:
        app: poshak-elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: poshak-elasticsearch
          env:
            - name: discovery.type
              value: single-node
          image: elasticsearch:7.8.0
          ports:
            - name: port9200
              containerPort: 9200
            - name: port9300
              containerPort: 9300
          volumeMounts:
            - name: elastic-persistent-claim
              mountPath: /usr/share/elasticsearch/data
              subPath:
          resources:
            { }
  volumeClaimTemplates:
    - metadata:
        name: elastic-persistent-claim
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: poshak-elasticsearch
spec:
  type: LoadBalancer
  selector:
    app: poshak-elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
