apiVersion: apps/v1
kind: Deployment
metadata:
  name: poshak-service-deployment
  labels:
    app: poshak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poshak-service
  template:
    metadata:
      labels:
        app: poshak-service
    spec:
      containers:
        - name: poshak-service
          image: registry.hub.docker.com/sourabhpayal/poshak-service
          ports:
            - name: port8090
              containerPort: 8090
            - name: port27017
              containerPort: 27017
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: poshak-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: poshak-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: poshak-configmap
                  key: database_url
          volumeMounts:
            - name: poshak-log-persistent-storage-claim
              mountPath: /home/sourabh
              subPath:
            resources:
              { }
  volumeClaimTemplates:
    - metadata:
        name: poshak-log-persistent-storage-claim
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: poshak-service
spec:
  type: LoadBalancer
  selector:
    app: poshak-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090