apiVersion: apps/v1
kind: Deployment
metadata:
  name: poshak-elasticsearch
  labels:
    app: poshak-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poshak-elasticsearch
  template:
    metadata:
      labels:
        app: poshak-elasticsearch
    spec:
      containers:
        - name: poshak-elasticsearch
          env:
            - name: discovery.type
              value: single-node
          image: elasticsearch:7.8.0
          ports:
            - name: port9200
              containerPort: 9200
            - name: port9300
              containerPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: poshak-elasticsearch
spec:
  type: LoadBalancer
  selector:
    app: poshak-elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
