apiVersion: apps/v1
kind: Deployment
metadata:
  name: poshak-logstash
  labels:
    app: poshak-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poshak-logstash
  template:
    metadata:
      labels:
        app: poshak-logstash
    spec:
      containers:
        - name: poshak-logstash
          env:
            - name: HTTP_HOST
              value: https://poshak-logstash-sr-sourabh.cloud.okteto.net
            - name: MONITORING_ELASTICSEARCH_HOSTS
              value: https://poshak-elasticsearch-sr-sourabh.cloud.okteto.net:443
          image: registry.hub.docker.com/sourabhpayal/poshak-logstash
          ports:
            - name: port5044
              containerPort: 5044
            - name: port9600
              containerPort: 9600
          #command:
            #- logstash
---
apiVersion: v1
kind: Service
metadata:
  name: poshak-logstash
spec:
  type: LoadBalancer
  selector:
    app: poshak-logstash
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044
