name: logstash-docker-image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image poshak-logstash 
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sourabhpayal/poshak-logstash
        tags: v1, latest
        registry: registry.hub.docker.com
        dockerfile: poshak-service/elk/LogstashDockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
