name: poshak-ml-service

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image poshak-ml-service
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sourabhpayal/poshak-ml-service
        tags: v1, latest
        registry: registry.hub.docker.com
        dockerfile: poshak-service/elk/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
